package com.example.healthanomaly.domain.model

/**
 * Represents a detected anomaly event.
 *
 * @property id Unique identifier (auto-generated by Room)
 * @property timestampMs When the anomaly was detected
 * @property type Type of anomaly
 * @property severity Severity level (1-10)
 * @property details Additional details about the anomaly
 * @property acknowledged Whether the user has acknowledged this event
 * @property archived Whether the event has been archived
 */
data class AnomalyEvent(
    val id: Long = 0,
    val timestampMs: Long,
    val type: AnomalyType,
    val severity: Int,
    val details: String,
    val acknowledged: Boolean = false,
    val archived: Boolean = false
)