package com.example.healthanomaly.domain.model

/**
 * Data class representing a window of extracted features from IMU data.
 * @property id Unique identifier (auto-generated by Room)
 * @property timestampMs Window end timestamp
 * @property windowSizeMs Window size in milliseconds (default 2000ms)
 * @property sampleCount Number of samples in this window
 * 
 * Accelerometer features
 * @property meanAccelX Mean X acceleration
 * @property meanAccelY Mean Y acceleration
 * @property meanAccelZ Mean Z acceleration
 * @property stdAccelX Std dev X acceleration
 * @property stdAccelY Std dev Y acceleration
 * @property stdAccelZ Std dev Z acceleration
 * @property rmsAccel RMS of acceleration magnitude
 * @property maxAccel Maximum acceleration magnitude
 * @property minAccel Minimum acceleration magnitude
 * @property jerkRms RMS of jerk (derivative of acceleration)
 * 
 * Gyroscope features
 * @property meanGyroX Mean X gyroscope
 * @property meanGyroY Mean Y gyroscope
 * @property meanGyroZ Mean Z gyroscope
 * @property stdGyroX Std dev X gyroscope
 * @property stdGyroY Std dev Y gyroscope
 * @property stdGyroZ Std dev Z gyroscope
 * @property rmsGyro RMS of gyroscope magnitude
 * 
 * Derived features
 * @property stepFreqHz Estimated step frequency in Hz
 * @property heartRateBpm Heart rate during this window (optional)
 */
data class FeatureWindow(
    val id: Long = 0,
    val timestampMs: Long,
    val windowSizeMs: Long = 2000L,
    val sampleCount: Int = 0,
    
    // Accelerometer statistics
    val meanAccelX: Float = 0f,
    val meanAccelY: Float = 0f,
    val meanAccelZ: Float = 0f,
    val stdAccelX: Float = 0f,
    val stdAccelY: Float = 0f,
    val stdAccelZ: Float = 0f,
    val rmsAccel: Float = 0f,
    val maxAccel: Float = 0f,
    val minAccel: Float = 0f,
    val jerkRms: Float = 0f,
    
    // Gyroscope statistics
    val meanGyroX: Float = 0f,
    val meanGyroY: Float = 0f,
    val meanGyroZ: Float = 0f,
    val stdGyroX: Float = 0f,
    val stdGyroY: Float = 0f,
    val stdGyroZ: Float = 0f,
    val rmsGyro: Float = 0f,
    
    // Derived features
    val stepFreqHz: Float = 0f,
    val heartRateBpm: Int? = null
)
